apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-pod
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: create-pod
  namespace: default
rules:
- apiGroup: ""
  resources: ["pods"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"] 
- apiGroup: ""
  resources: ["services"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
- apiGroup: ""
  resources: ["ingress"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
 metadata:
   name: create-pod
   namespace: default
 subjects:
 - kind: ServiceAccount
   name: create-pod
   namespace: default	